dist: xenial
language: cpp

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake libboost-system-dev libssl-dev libmysqlclient-dev realpath

script:
  - cmake .
  - sudo make install
  - ctest
